# Generated by Django 4.2.5 on 2023-11-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_products_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('D', 'Dress'), ('B', 'Bag'), ('S', 'Shoes'), ('A', 'Accesories'), ('BS', 'Best Selling'), ('AL', 'All')], max_length=2),
        ),
    ]
