# Generated by Django 4.2.5 on 2023-11-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Dress', 'D'), ('Bag', 'B'), ('Shoes', 'S'), ('Accesories', 'A'), ('Best_Selling', 'BS'), ('All', 'AL')], max_length=12),
        ),
    ]
